# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Projects/WaveGen/Basys-3-Master.xdc

# Block Designs: bd/WaveGen/WaveGen.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen || ORIG_REF_NAME==WaveGen} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_Sseg_decoder_0_0/WaveGen_Sseg_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_Sseg_decoder_0_0 || ORIG_REF_NAME==WaveGen_Sseg_decoder_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_xadc_wiz_0_0/WaveGen_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_xadc_wiz_0_0 || ORIG_REF_NAME==WaveGen_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_xlconstant_0_0/WaveGen_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_xlconstant_0_0 || ORIG_REF_NAME==WaveGen_xlconstant_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_ADC_Buff_0_0/WaveGen_ADC_Buff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_ADC_Buff_0_0 || ORIG_REF_NAME==WaveGen_ADC_Buff_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_B4DC_0_0/WaveGen_B4DC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_B4DC_0_0 || ORIG_REF_NAME==WaveGen_B4DC_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_CLK_KHZ_10_50_0_0/WaveGen_CLK_KHZ_10_50_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_CLK_KHZ_10_50_0_0 || ORIG_REF_NAME==WaveGen_CLK_KHZ_10_50_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_BarGraph_0_0/WaveGen_BarGraph_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_BarGraph_0_0 || ORIG_REF_NAME==WaveGen_BarGraph_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_Recursive_Filter_0_0/WaveGen_Recursive_Filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_Recursive_Filter_0_0 || ORIG_REF_NAME==WaveGen_Recursive_Filter_0_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_Recursive_Filter_1_0/WaveGen_Recursive_Filter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_Recursive_Filter_1_0 || ORIG_REF_NAME==WaveGen_Recursive_Filter_1_0} -quiet] -quiet

# IP: bd/WaveGen/ip/WaveGen_Advanced_Timer_0_0/WaveGen_Advanced_Timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WaveGen_Advanced_Timer_0_0 || ORIG_REF_NAME==WaveGen_Advanced_Timer_0_0} -quiet] -quiet

# XDC: c:/Xilinx/Projects/WaveGen/WaveGen.gen/sources_1/bd/WaveGen/WaveGen_ooc.xdc
